name: PMD static code analysis

on:
  push:


jobs:
  test:
    name: Run PMD analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: "Static analysis"
        uses: pmd/pmd-github-action@v1
        with:
          version: "7.0.0-rc4"
          sourcePath: "src/main"
          rulesets: 'rulesets/java/quickstart.xml'
          analyzeModifiedFilesOnly: false
      - name: "Upload SARIF file"
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pmd-report.sarif